### ISSUE TITLE
Cannot update to 1.3.0

### ISSUE THREAD

**Issue by kkmuffme** [burnpiro/puppeteer-screenshot-tester#34]
**Describe the bug**

```
npm ERR! Error while executing:
npm ERR! /bin/git ls-remote -h -t git://github.com/burnpiro/node-resemble.js.git
npm ERR!
npm ERR! fatal: cannot come back to cwd: Permission denied
npm ERR!
npm ERR! exited with error code: 128
```

**Please complete the following information:**
 - OS: Centos 8
 - node v13.13.0, npm 6.14.7

**To Reproduce**
`npm install -g  puppeteer-screenshot-tester@1.3.0`

**Expected behavior**
Update to 1.3.0

**Stack Trace**

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'puppeteer-screenshot-tester@1.3.0'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.13.0
4 verbose npm-session 5c430a1aed7d5a5d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/puppeteer-screenshot-tester 75ms (from cache)
8 silly pacote version manifest for puppeteer-screenshot-tester@1.3.0 fetched in 139ms
9 timing stage:loadCurrentTree Completed in 294ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 12ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule puppeteer-screenshot-tester@1.3.0 checking installable status
17 silly removeObsoleteDep removing puppeteer-screenshot-tester@1.1.1 from the tree as its been replaced by a newer version or is no longer required
18 silly removeObsoleteDep removing fs@0.0.1-security from the tree as its been replaced by a newer version or is no longer required
19 silly removeObsoleteDep removing node-resemble-js@0.2.0 from the tree as its been replaced by a newer version or is no longer required
20 silly removeObsoleteDep removing jpeg-js@0.2.0 from the tree as its been replaced by a newer version or is no longer required
21 silly removeObsoleteDep removing pngjs@2.2.0 from the tree as its been replaced by a newer version or is no longer required
22 silly removeObsoleteDep removing parent-module@0.1.0 from the tree as its been replaced by a newer version or is no longer required
23 silly removeObsoleteDep removing callsites@1.0.1 from the tree as its been replaced by a newer version or is no longer required
24 silly removeObsoleteDep removing path@0.12.7 from the tree as its been replaced by a newer version or is no longer required
25 silly removeObsoleteDep removing process@0.11.10 from the tree as its been replaced by a newer version or is no longer required
26 silly removeObsoleteDep removing util@0.10.4 from the tree as its been replaced by a newer version or is no longer required
27 silly removeObsoleteDep removing inherits@2.0.3 from the tree as its been replaced by a newer version or is no longer required
28 silly fetchPackageMetaData error for node-resemble-js@git://github.com/burnpiro/node-resemble.js.git#0.3.0 Error while executing:
28 silly fetchPackageMetaData /bin/git ls-remote -h -t git://github.com/burnpiro/node-resemble.js.git
28 silly fetchPackageMetaData
28 silly fetchPackageMetaData fatal: cannot come back to cwd: Permission denied
28 silly fetchPackageMetaData
28 silly fetchPackageMetaData exited with error code: 128
29 http fetch GET 304 https://registry.npmjs.org/fs 257ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/parent-module 245ms (from cache)
31 silly pacote range manifest for parent-module@^0.1.0 fetched in 263ms
32 silly resolveWithNewModule parent-module@0.1.0 checking installable status
33 silly pacote range manifest for fs@^0.0.1-security fetched in 280ms
34 silly resolveWithNewModule fs@0.0.1-security checking installable status
35 http fetch GET 304 https://registry.npmjs.org/path 303ms (from cache)
36 silly pacote range manifest for path@^0.12.7 fetched in 313ms
37 silly resolveWithNewModule path@0.12.7 checking installable status
38 timing stage:rollbackFailedOptional Completed in 1ms
39 timing stage:runTopLevelLifecycles Completed in 648ms
40 verbose stack Error: exited with error code: 128
40 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/util/finished.js:12:19)
40 verbose stack     at ChildProcess.emit (events.js:315:20)
40 verbose stack     at maybeClose (internal/child_process.js:1026:16)
40 verbose stack     at Socket.<anonymous> (internal/child_process.js:441:11)
40 verbose stack     at Socket.emit (events.js:315:20)
40 verbose stack     at Pipe.<anonymous> (net.js:674:12)
41 verbose cwd /root
42 verbose Linux 4.18.0-147.5.1.el8_1.x86_64
43 verbose argv "/usr/bin/node" "/bin/npm" "install" "-g" "puppeteer-screenshot-tester@1.3.0"
44 verbose node v13.13.0
45 verbose npm  v6.14.4
46 error Error while executing:
46 error /bin/git ls-remote -h -t git://github.com/burnpiro/node-resemble.js.git
46 error
46 error fatal: cannot come back to cwd: Permission denied
46 error
46 error exited with error code: 128
47 verbose exit [ 1, true ]
```

**Comment by burnpiro** [comment]
There was a problem with the dependency `node-resemble`, already patched in 1.3.1
